import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { findAppRoot, findPageRoot, listAppsOrExit } from "./apps.mjs";
import { findChannel, readCommandLine } from "./channels.mjs";
import { pinPageFiles, readPageFiles } from "./page-files.mjs";
import { readVersion } from "./release.mjs";

const root = new URL("../", import.meta.url);
/** @param {string} app */
const findOutput = (app) => fileURLToPath(new URL("worker/dist/worker.mjs", findAppRoot(app)));
/** @param {string} app */
const describeBanner = (app) =>
  `// Generated by worker/build.mjs from apps/${app}/worker/src/ and apps/${app}/page/. Edit those and rebuild.`;

const runGit = (args) => execFileSync("git", args, { cwd: fileURLToPath(root), encoding: "utf8" });

// A branch on another channel hasn't merged, so its version is main's where the branch left it.
/** @param {(args: string[]) => string} git */
function readBranchBase(git) {
  try {
    return git(["merge-base", "HEAD", `origin/${findChannel().branch}`]).trim();
  } catch {
    return null;
  }
}

/**
 * Names the commit being built and the app's version, for the page's settings, with the channel's
 * label on the version of any but production. Only deploys go live, so the build time is the
 * deploy time.
 * @param {string} app
 * @param {(args: string[]) => string} [git]
 * @param {Date} [now]
 * @param {string} [channel]
 * @returns {{ version: string | null, commit: string, builtAt: string } | null}
 */
export function readRelease(app, git = runGit, now = new Date(), channel = "production") {
  let commit;
  try {
    commit = git(["log", "-1", "--format=%h"]).trim();
  } catch {
    return null;
  }
  const builtAt = now.toISOString();
  const { label } = findChannel(channel);
  if (!label) return { version: readVersion(app, git), commit, builtAt };
  const base = readBranchBase(git);
  const version = base && readVersion(app, git, base);
  return { version: `${version ?? commit}-${label}`, commit, builtAt };
}

const HOME_SCREEN_TITLE = /(<meta name="apple-mobile-web-app-title" content=")([^"]+)(")/;

/**
 * @param {{ contentType: string, text?: string, base64?: string }} file
 * @param {string} label
 */
function labelManifest(file, label) {
  const manifest = JSON.parse(file.text ?? "{}");
  const text = JSON.stringify({
    ...manifest,
    name: `${manifest.name} ${label}`,
    short_name: `${manifest.short_name} ${label}`,
  });
  return { ...file, text };
}

/**
 * @param {{ contentType: string, text?: string, base64?: string }} file
 * @param {string} label
 */
const labelHomeScreenTitle = (file, label) => ({
  ...file,
  text: file.text?.replace(
    HOME_SCREEN_TITLE,
    (_tag, start, title, end) => `${start}${title} ${label}${end}`,
  ),
});

/**
 * The page files with the channel's label on the name the Home Screen gives the page, so a phone
 * with both channels tells them apart.
 * @param {ReturnType<typeof readPageFiles>} files
 * @param {string | null} label
 */
export function labelChannelFiles(files, label) {
  if (!label) return files;
  const labeled = Object.entries(files).map(([path, file]) => {
    if (path === "manifest.webmanifest") return [path, labelManifest(file, label)];
    if (path.endsWith(".html")) return [path, labelHomeScreenTitle(file, label)];
    return [path, file];
  });
  return Object.fromEntries(labeled);
}

/**
 * @param {string} app
 * @param {ReturnType<typeof readRelease>} release
 * @param {string} [channel]
 */
export function listBundledFiles(app, release, channel = "production") {
  const files = labelChannelFiles(readPageFiles(findPageRoot(app)), findChannel(channel).label);
  if (!release) return files;
  return {
    ...pinPageFiles(files, release.commit),
    "version.json": { contentType: "application/json", text: JSON.stringify(release) },
  };
}

// Node reads the page from disk through #page-files/<app>; the Worker has no disk, so the build
// embeds it.
const embedPageFiles = (app, release, channel) => ({
  name: "embed-page-files",
  setup(bundler) {
    bundler.onResolve({ filter: new RegExp(`^#page-files/${app}$`) }, () => ({
      path: "page-files",
      namespace: "page-files",
    }));
    bundler.onLoad({ filter: /.*/, namespace: "page-files" }, () => ({
      contents: `export default ${JSON.stringify(listBundledFiles(app, release, channel))};`,
      loader: "js",
    }));
  },
});

/**
 * @param {string} app
 * @param {{ channel?: string, release?: ReturnType<typeof readRelease> }} [options]
 */
export async function buildWorker(
  app,
  { channel = "production", release = readRelease(app, undefined, undefined, channel) } = {},
) {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("worker/src/index.js", findAppRoot(app)))],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    banner: { js: describeBanner(app) },
    plugins: [embedPageFiles(app, release, channel)],
    write: false,
  });
  return result.outputFiles[0].text;
}

// With no app named, builds them all.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { positionals, channel } = readCommandLine(process.argv.slice(2));
  for (const app of listAppsOrExit(positionals[0])) {
    const built = await buildWorker(app, { channel });
    const output = findOutput(app);
    mkdirSync(path.dirname(output), { recursive: true });
    writeFileSync(output, built);
    console.log(`Wrote ${output} (${built.length} bytes)`);
  }
}
